activeEnvironment: test
environments:
  test:
    browser:
      browserName: chrome
      appUrl: https://seleniumui.moderntester.pl/form.php
    user:
      firstName: Brad
      lastName: Pitt
      email: bradpitt@gmail.com
      age: 50
  prod:
    browser:
      browserName: chrome
      appUrl: https://seleniumui.moderntester.pl/form.php
    user:
      firstName: Adam
      lastName: Małysz
      email: adamskacze@gmail.com
      age: 35

