activeEnvironment: test
environments:
  test:
    browser:
      browserName: chrome
      appUrl: https://seleniumui.moderntester.pl/form.php
    testData:
      firstName: Kamil
      lastName: Stoch
      email: KamilSkacze@gmail.com
      validation: Form send with success
      age: 22
      asdasdas: dasdas
      asdasasd: asddas



  prod:
    browser:
      browserName: chrome
      appUrl: https://seleniumui.moderntester.pl/form.php
    user:
      firstName: Adam
      lastName: Małysz
      email: adamskacze@gmail.com
      validation: Form send with success
      age: 35
      asdas: asdsdas


